vich_uploader:
    db_driver: orm

    mappings:
        user:
            uri_prefix: '%app.path.pictures%'
            upload_destination: '%kernel.project_dir%/public%app.path.pictures%'
            #namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_update: false
            delete_on_remove: true
