version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        # expose:
        #    - 3306
        # ports:
        #    - "3306:3306"

        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bobo-bidon
            MYSQL_USER: root
            MYSQL_PASSWORD: dodzmo30

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8081:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8001:80

    node:
      image: node:13-alpine
      user: "node"
      volumes:
        - .:/home/wwwroot/sf4
      working_dir: /home/wwwroot/sf4
      ports:
        - 8080:8080
      # Others commands :
      # yarn install // Install assets
      # yarn encore dev --watch // Watch and compile assets
      # yarn encore dev-server --host 0.0.0.0 --port 8080 --disable-host-check // Watch and compile assets + Hot reload
      command: "ash -c \"yarn install && yarn encore dev-server --host 0.0.0.0 --port 8080 --disable-host-check\""
